# Generated by Django 5.1.4 on 2024-12-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (
                                "multiple",
                                "ONE CORRECT ANSWER AND SEVERAL INCORRECT ANSWERS",
                            ),
                            ("boolean", "TRUE OR FALSE"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=10,
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("question", models.TextField(max_length=1000)),
                ("correct_answer", models.TextField(max_length=255)),
                ("incorrect_answers", models.JSONField()),
            ],
        ),
    ]
